[package]
name = "persistence"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
name = "persistence"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1"
serde = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true

